/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AuditLog {
  'id' : string,
  'userRole' : string,
  'action' : string,
  'userId' : string,
  'timestamp' : bigint,
  'details' : string,
  'entityType' : string,
}
export interface HighRiskCohort {
  'id' : string,
  'status' : string,
  'urgency' : string,
  'riskCriteria' : string,
  'flagDate' : bigint,
  'cohortSize' : bigint,
  'providerId' : string,
}
export interface IndicatorResult {
  'id' : string,
  'trend' : string,
  'nationalBenchmark' : number,
  'quarter' : string,
  'rate' : number,
  'indicatorCode' : string,
  'indicatorName' : string,
  'dimension' : string,
  'providerId' : string,
  'quintileRank' : bigint,
}
export interface NationalOverviewStats {
  'dataQualityScore' : number,
  'screeningComplianceRate' : number,
  'totalProviders' : bigint,
  'highRiskFlagged' : bigint,
  'avgPreventiveScore' : number,
  'totalResidents' : bigint,
  'avgSafetyScore' : number,
}
export interface ProviderScorecard {
  'id' : string,
  'experienceScore' : number,
  'overallScore' : number,
  'quarter' : string,
  'safetyScore' : number,
  'preventiveScore' : number,
  'providerId' : string,
  'equityScore' : number,
  'quintileRank' : bigint,
}
export interface ScreeningWorkflow {
  'id' : string,
  'status' : string,
  'completionTimeHours' : number,
  'dueDate' : bigint,
  'screeningType' : string,
  'providerId' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAuditLogEntry' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllHighRiskCohorts' : ActorMethod<[], Array<HighRiskCohort>>,
  'getAllScreeningWorkflows' : ActorMethod<[], Array<ScreeningWorkflow>>,
  'getAuditLogs' : ActorMethod<[], Array<AuditLog>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHighRiskCohorts' : ActorMethod<[string], Array<HighRiskCohort>>,
  'getIndicatorResults' : ActorMethod<[string, string], Array<IndicatorResult>>,
  'getNationalOverviewStats' : ActorMethod<[string], NationalOverviewStats>,
  'getScorecardsByProvider' : ActorMethod<[string], Array<ProviderScorecard>>,
  'getScreeningWorkflows' : ActorMethod<[string], Array<ScreeningWorkflow>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateScreeningStatus' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];