/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const HighRiskCohort = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'urgency' : IDL.Text,
  'riskCriteria' : IDL.Text,
  'flagDate' : IDL.Int,
  'cohortSize' : IDL.Nat,
  'providerId' : IDL.Text,
});
export const ScreeningWorkflow = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'completionTimeHours' : IDL.Float64,
  'dueDate' : IDL.Int,
  'screeningType' : IDL.Text,
  'providerId' : IDL.Text,
});
export const AuditLog = IDL.Record({
  'id' : IDL.Text,
  'userRole' : IDL.Text,
  'action' : IDL.Text,
  'userId' : IDL.Text,
  'timestamp' : IDL.Int,
  'details' : IDL.Text,
  'entityType' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const IndicatorResult = IDL.Record({
  'id' : IDL.Text,
  'trend' : IDL.Text,
  'nationalBenchmark' : IDL.Float64,
  'quarter' : IDL.Text,
  'rate' : IDL.Float64,
  'indicatorCode' : IDL.Text,
  'indicatorName' : IDL.Text,
  'dimension' : IDL.Text,
  'providerId' : IDL.Text,
  'quintileRank' : IDL.Nat,
});
export const NationalOverviewStats = IDL.Record({
  'dataQualityScore' : IDL.Float64,
  'screeningComplianceRate' : IDL.Float64,
  'totalProviders' : IDL.Nat,
  'highRiskFlagged' : IDL.Nat,
  'avgPreventiveScore' : IDL.Float64,
  'totalResidents' : IDL.Nat,
  'avgSafetyScore' : IDL.Float64,
});
export const ProviderScorecard = IDL.Record({
  'id' : IDL.Text,
  'experienceScore' : IDL.Float64,
  'overallScore' : IDL.Float64,
  'quarter' : IDL.Text,
  'safetyScore' : IDL.Float64,
  'preventiveScore' : IDL.Float64,
  'providerId' : IDL.Text,
  'equityScore' : IDL.Float64,
  'quintileRank' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAuditLogEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllHighRiskCohorts' : IDL.Func([], [IDL.Vec(HighRiskCohort)], ['query']),
  'getAllScreeningWorkflows' : IDL.Func(
      [],
      [IDL.Vec(ScreeningWorkflow)],
      ['query'],
    ),
  'getAuditLogs' : IDL.Func([], [IDL.Vec(AuditLog)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHighRiskCohorts' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(HighRiskCohort)],
      ['query'],
    ),
  'getIndicatorResults' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(IndicatorResult)],
      ['query'],
    ),
  'getNationalOverviewStats' : IDL.Func(
      [IDL.Text],
      [NationalOverviewStats],
      ['query'],
    ),
  'getScorecardsByProvider' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ProviderScorecard)],
      ['query'],
    ),
  'getScreeningWorkflows' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ScreeningWorkflow)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateScreeningStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const HighRiskCohort = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'urgency' : IDL.Text,
    'riskCriteria' : IDL.Text,
    'flagDate' : IDL.Int,
    'cohortSize' : IDL.Nat,
    'providerId' : IDL.Text,
  });
  const ScreeningWorkflow = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'completionTimeHours' : IDL.Float64,
    'dueDate' : IDL.Int,
    'screeningType' : IDL.Text,
    'providerId' : IDL.Text,
  });
  const AuditLog = IDL.Record({
    'id' : IDL.Text,
    'userRole' : IDL.Text,
    'action' : IDL.Text,
    'userId' : IDL.Text,
    'timestamp' : IDL.Int,
    'details' : IDL.Text,
    'entityType' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const IndicatorResult = IDL.Record({
    'id' : IDL.Text,
    'trend' : IDL.Text,
    'nationalBenchmark' : IDL.Float64,
    'quarter' : IDL.Text,
    'rate' : IDL.Float64,
    'indicatorCode' : IDL.Text,
    'indicatorName' : IDL.Text,
    'dimension' : IDL.Text,
    'providerId' : IDL.Text,
    'quintileRank' : IDL.Nat,
  });
  const NationalOverviewStats = IDL.Record({
    'dataQualityScore' : IDL.Float64,
    'screeningComplianceRate' : IDL.Float64,
    'totalProviders' : IDL.Nat,
    'highRiskFlagged' : IDL.Nat,
    'avgPreventiveScore' : IDL.Float64,
    'totalResidents' : IDL.Nat,
    'avgSafetyScore' : IDL.Float64,
  });
  const ProviderScorecard = IDL.Record({
    'id' : IDL.Text,
    'experienceScore' : IDL.Float64,
    'overallScore' : IDL.Float64,
    'quarter' : IDL.Text,
    'safetyScore' : IDL.Float64,
    'preventiveScore' : IDL.Float64,
    'providerId' : IDL.Text,
    'equityScore' : IDL.Float64,
    'quintileRank' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAuditLogEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllHighRiskCohorts' : IDL.Func(
        [],
        [IDL.Vec(HighRiskCohort)],
        ['query'],
      ),
    'getAllScreeningWorkflows' : IDL.Func(
        [],
        [IDL.Vec(ScreeningWorkflow)],
        ['query'],
      ),
    'getAuditLogs' : IDL.Func([], [IDL.Vec(AuditLog)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHighRiskCohorts' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(HighRiskCohort)],
        ['query'],
      ),
    'getIndicatorResults' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(IndicatorResult)],
        ['query'],
      ),
    'getNationalOverviewStats' : IDL.Func(
        [IDL.Text],
        [NationalOverviewStats],
        ['query'],
      ),
    'getScorecardsByProvider' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ProviderScorecard)],
        ['query'],
      ),
    'getScreeningWorkflows' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ScreeningWorkflow)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateScreeningStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };